server:
  port: 8080

management:
  security:
    enabled: false

spring:
  application:
    name: edge-service
  checkToken:
    serviceUrl: http://localhost:8080/uaa/oauth/check_token
    clientId: clientId
    clientSecret: clientSecret

zuul:
  routes:
    # Authentication
    uaa:
      path: /uaa/**
      sensitive-headers: true
      serviceId: auth-service
    # Microservices
    uuid:
      path: /uuid/**
      serviceId: uuid-service