server:
  port: 8080

management:
  security:
    enabled: false

spring:
  application:
    name: edge-service

authorizationServer:
    userInfoUrl: http://localhost:9000/user
    oauthToken:
      checkUrl: http://localhost:9000/oauth/check_token
      client:
        id: clientId
        secret: clientSecret

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 126000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

zuul:
  routes:
    # Authentication
    uaa:
      path: /uaa/**
      sensitive-headers: true
      serviceId: auth-service
    # Microservices
    hash:
      path: /hash-service/**
      serviceId: hash-service
    photo:
      path: /photo-service/**
      serviceId: photo-service
  # Authentication Policy Rules
  auth:
    rules:
      - hash:
          path: /hash-service/**
          role: USER
      - photo:
          path: /photo-service/**
          role: USER
