server:
  port: 8080

management:
  security:
    enabled: false

spring:
  application:
    name: edge-service

zuul:
  routes:
    # Authentication
    uaa:
      path: /uaa/**
      sensitive-headers: true
      serviceId: auth-service
    # Microservices
    uuid:
      path: /uuid/**
      serviceId: uuid-service