server:
  port: 8080

management:
  security:
    enabled: false

spring:
  application:
    name: edge-service
  oauth:
    checkTokenUrl: http://localhost:8080/uaa/oauth/check_token
    client:
      id: clientId
      secret: clientSecret

zuul:
  routes:
    # Authentication
    uaa:
      path: /uaa/**
      sensitive-headers: true
      serviceId: auth-service
    # Microservices
    hash:
      path: /hash/**
      serviceId: hash-service
    photo:
      path: /photo/**
      serviceId: photo-service