version: '2.3'

services:
  mysql:
    ports:
      - "13306:3306"
  eureka:
    ports:
      - "8761:8761"
  edge:
    ports:
      - "8080:8080"
  auth:
    ports:
      - "9000:9000"
  hash:
    ports:
      - "8081:8081"
  photo:
    ports:
      - "8082:8082"