version: '2.3'

services:
  # Database
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - persistent-data:/var/lib/mysql
    command: [--ssl=0]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      interval: 10s
      timeout: 60s
      retries: 5
    ports:
      - "13306:3306"
  # Eurea discovery service
  eureka-svc:
    build:
      context: infrastructure/eureka-service/
    ports:
      - "8761:8761"
  # Edge gateway service
  edge-svc:
    build:
      context: infrastructure/edge-service/
    ports:
      - "8080:8080"

volumes:
  persistent-data:

