version: '2.3'

services:
  # Database
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - persistent-data:/var/lib/mysql
    command: [--ssl=0]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      interval: 10s
      timeout: 60s
      retries: 5
    ports:
      - "13306:3306"

  # Eurea discovery service
  eureka-svc:
    build:
      context: infrastructure/eureka-service/
    healthcheck:
      test: "wget -q -T 1 -s http://localhost:8761/actuator/health"
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - "8761:8761"

  # Edge gateway service
  edge-svc:
    build:
      context: infrastructure/edge-service/
    healthcheck:
      test: "wget -q -T 1 -s http://localhost:8080/actuator/health"
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      eureka-svc:
        condition: service_healthy
    volumes:
      - ./config/edge-svc.props.yml:/service/application.yml:ro
    ports:
      - "8080:8080"

  # Auth service
  auth-svc:
    build:
      context: infrastructure/auth-service/
    healthcheck:
      test: "wget -q -T 1 -s http://localhost:9000/actuator/health"
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      mysql:
        condition: service_healthy
      eureka-svc:
        condition: service_healthy
    volumes:
      - ./config/auth-svc.props.yml:/service/application.yml:ro
    ports:
      - "9000"

volumes:
  persistent-data:

