version: '2.3'

services:
  hash:
    build:
      context: microservices/hash-service/
    healthcheck:
      test: "wget -q -T 1 -s http://localhost:8081/actuator/health"
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      eureka:
        condition: service_healthy
    ports:
      - "8081:8081"

