version: '2.3'

services:
  mysql:
    volumes:
      - persistent-data:/var/lib/mysql
    expose:
      - "3306"
  eureka:
    ports:
      - "8761:8761"
  edge:
    ports:
      - "8080:8080"
  auth:
    expose:
      - "9000"
  hash:
    expose:
      - "8081"
  photo:
    expose:
      - "8082"

volumes:
  persistent-data: