version: '2.3'

services:
  mysql:
    volumes:
      - persistent-data:/var/lib/mysql
    ports:
      - "3306"
  auth:
    ports:
      - "9000"
  hash:
    ports:
      - "8081"

volumes:
  persistent-data: