logging:
  config: /service/logback.xml

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/auth_service?createDatabaseIfNotExist=true
    username: root
    password: root
  flyway:
    locations: classpath:/db/migration/schema

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
