spring:
  datasource:
    url: jdbc:mysql://mysql:3306/auth_service?createDatabaseIfNotExist=true
    username: root
    password: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-svc:8761/eureka/
