logging:
  config: /service/logback.xml

authorizationServer:
    userInfoUrl: http://auth:9000/user
    oauthToken:
      checkUrl: http://auth:9000/oauth/check_token
      client:
        id: clientId
        secret: clientSecret

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
