spring:
  datasource:
    url: jdbc:mysql://mysql:3306/photo_service?createDatabaseIfNotExist=true
    username: root
    password: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
