server:
  port: 9000

spring:
  application:
    name: auth-service

jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:13306/oauth2?createDatabaseIfNotExist=true
  user: root
  pass: root
