server:
  port: 9000

spring:
  application:
    name: auth-service
  datasource:
      url: jdbc:mysql://localhost:13306/auth_service?createDatabaseIfNotExist=true
      username: root
      password: root
      testWhileIdle: true
      validationQuery: SELECT 1

jpa:
  hibernate:
    show-sql: true
    ddl-auto: create-drop
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    dialect: org.hibernate.dialect.MySQL5Dialect
